name: Audit

on:
  push:
    branches:
      - develop
      - ft-ci-cd
  pull_request:
    branches: [main]

jobs:
  audit:
    name: Run go on ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      # - name: download dependencies
      #   run:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: verify dependencies
        run: go mod verify

      - name: Run go fmt
        run: go fmt ./...

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run go mod vet
        run: go vet ./...

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck
        run: staticcheck ./...

      - name: install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run  golint
        run: golint ./...

      - name: Run tetsts
        run: go tests -race -vet=off ./...
