name: Publish to Docker hub

on:
  push:
    branches: ## [main]
      - develop
      - ft-ci-cd

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    steps:
      - name: docker login
      - uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          pasword: ${{secrets.DOCKER_PASSWORD}}
        # env:
        #   DOCKER_USER:${{secrets.DOCKER_USER}}
        #   DOCKER_PASSWORD:${{secrets.DOCKER_PASSWORD}}
        # run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build docker image
        run: docker build . --file Dockerfile --tag auth/auth-service

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}//rabin-nyaundi
