name: Publish to Docker hub

on:
  push:
    branches: 
      - develop
      - ft-ci-cd

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to Dockerhub
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}