name: Audit

on:
  push:
    branches:
      - develop
      - ft-ci-cd
  pull_request:
    branches:
      - develop
      - main

jobs:
  audit:
    name: Run go on ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Verify dependencies
      - name: verify dependencies
        run: go mod verify

      #  format code with fmt package
      - name: Run go fmt
        run: go fmt ./...

      # run go tidy to tidify deendencies
      - name: Run go mod tidy
        run: go mod tidy

      # vet dependencies
      - name: Run go mod vet
        run: go vet ./...

      #  install staticcheck
      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck
        run: staticcheck ./...

      # install golint for liniting code
      - name: install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run  golint
        run: golint ./...

      # run tests
      # - name: Run tests
      #   run: go test -race -vet=off ./...
