name: Publish to Docker hub

on:
  push:
    branches: ## [main]
      - develop
      - ft-ci-cd

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to Dockerhub
      - uses: actions/checkout@v3