name: Publish to Docker hub

on:
  push:
    branches: ## [main]
      - develop
      - ft-ci-cd

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
    
      #  set up doker 
      - name: Login to Dockerhub
      - uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      # - name: Build docker image
      #   run: docker build . --file Dockerfile --tag auth/auth-service

      # - name: Docker push
      #   run: docker push ${{secrets.DOCKER_USER}}//rabin-nyaundi
