name: Publish Image to dockerhub

on:
  push:
    branches:
      tags:
        - "*"
      # - develop
      # - ft-ci-cd
  pull_request:
    branches:
      - develop
      - main

jobs:
  audit:
    name: Publish image to docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      # Login to docker hub
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker build image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/auth-service:${{ github.ref_name }}

      - name: Push Image
        run: docker push ${{secrets.DOCKER_USER}}/auth-service
